// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_concordance
Rcpp::NumericVector cpp_concordance(const Rcpp::NumericVector& p, const Rcpp::NumericVector& r);
RcppExport SEXP _scorecraft_cpp_concordance(SEXP pSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_concordance(p, r));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cor_matrix
arma::mat cpp_cor_matrix(const Rcpp::List& cols, const bool spearman, const int nthreads);
RcppExport SEXP _scorecraft_cpp_cor_matrix(SEXP colsSEXP, SEXP spearmanSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< const bool >::type spearman(spearmanSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cor_matrix(cols, spearman, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ecl_paths
Rcpp::List cpp_ecl_paths(SEXP h, SEXP L, SEXP E, SEXP P, SEXP r, const int n, const int H, const int hz, const bool discount, const Rcpp::LogicalVector& stage3, SEXP z, SEXP pd_mult, SEXP lgd_add, SEXP ead_mult, const double rho, const int nthreads);
RcppExport SEXP _scorecraft_cpp_ecl_paths(SEXP hSEXP, SEXP LSEXP, SEXP ESEXP, SEXP PSEXP, SEXP rSEXP, SEXP nSEXP, SEXP HSEXP, SEXP hzSEXP, SEXP discountSEXP, SEXP stage3SEXP, SEXP zSEXP, SEXP pd_multSEXP, SEXP lgd_addSEXP, SEXP ead_multSEXP, SEXP rhoSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type E(ESEXP);
    Rcpp::traits::input_parameter< SEXP >::type P(PSEXP);
    Rcpp::traits::input_parameter< SEXP >::type r(rSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type H(HSEXP);
    Rcpp::traits::input_parameter< const int >::type hz(hzSEXP);
    Rcpp::traits::input_parameter< const bool >::type discount(discountSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type stage3(stage3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pd_mult(pd_multSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lgd_add(lgd_addSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ead_mult(ead_multSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ecl_paths(h, L, E, P, r, n, H, hz, discount, stage3, z, pd_mult, lgd_add, ead_mult, rho, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tier_dp
Rcpp::List cpp_tier_dp(const Rcpp::NumericVector& e, const Rcpp::NumericVector& n, const Rcpp::NumericVector& vol, const Rcpp::NumericVector& e_raw, const Rcpp::NumericVector& n_raw, const int L, const int criterion, const double min_share, const double min_events, const double alpha);
RcppExport SEXP _scorecraft_cpp_tier_dp(SEXP eSEXP, SEXP nSEXP, SEXP volSEXP, SEXP e_rawSEXP, SEXP n_rawSEXP, SEXP LSEXP, SEXP criterionSEXP, SEXP min_shareSEXP, SEXP min_eventsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type e_raw(e_rawSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type n_raw(n_rawSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< const double >::type min_share(min_shareSEXP);
    Rcpp::traits::input_parameter< const double >::type min_events(min_eventsSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tier_dp(e, n, vol, e_raw, n_raw, L, criterion, min_share, min_events, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scorecraft_cpp_concordance", (DL_FUNC) &_scorecraft_cpp_concordance, 2},
    {"_scorecraft_cpp_cor_matrix", (DL_FUNC) &_scorecraft_cpp_cor_matrix, 3},
    {"_scorecraft_cpp_ecl_paths", (DL_FUNC) &_scorecraft_cpp_ecl_paths, 16},
    {"_scorecraft_cpp_tier_dp", (DL_FUNC) &_scorecraft_cpp_tier_dp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_scorecraft(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
