#' Synthetic example data
#'
#' A fabricated table so that every example and every vignette runs without
#' a database. On purpose, it carries the defects real data has: sentinel
#' `-999` in several masses (`vl_hist_*`), missing values (`vl_parcial_*`),
#' a column that only degrades in the last period (`vl_tardio`), constant,
#' near-constant, exact duplicate, high cardinality, a redundant pair and
#' pure noise. Without them, the audit funnel would have nothing to show.
#'
#' @format A `data.frame` with 4,200 rows and 41 columns:
#' \describe{
#'   \item{`id`}{Identifier (never a candidate; goes in `drop`).}
#'   \item{`ref_date`}{Monthly reference date, six periods; the key of the
#'     out-of-time split.}
#'   \item{`vl_score_01` to `vl_score_12`}{Numerics with decreasing signal.}
#'   \item{`vl_hist_01` to `vl_hist_05`}{Numerics with an increasing mass of
#'     sentinel `-999`; the signal is in the absence.}
#'   \item{`vl_parcial_01` to `vl_parcial_03`}{Numerics with genuine `NA`.}
#'   \item{`vl_tardio`}{Numeric with `NA`/sentinel in the last period only.}
#'   \item{`vl_ruido_01` to `vl_ruido_06`}{Pure noise.}
#'   \item{`vl_constante`, `vl_quase_const`, `ds_constante`, `vl_duplicada`,
#'     `vl_redundante`, `ds_alta_card`}{Structural pathologies.}
#'   \item{`ds_regiao`, `ds_faixa`, `ds_canal`, `ds_optin`}{Categoricals with
#'     signal; `ds_optin` has `NA`.}
#'   \item{`default`}{Risk target (0/1, about 10% events).}
#'   \item{`churn`}{Propensity target (0/1, about 25% events), for the
#'     portfolio examples.}
#' }
#' @source Generated by `data-raw/scr_demo.R`, seed `20260903`.
#' @family data
#' @examples
#' str(scr_demo[, 1:6])
#' mean(scr_demo$default)
"scr_demo"
